services:
  mysql:
    image: mariadb:10.5
    environment:
    - MYSQL_DATABASE=data-keeper
    - MYSQL_ROOT_PASSWORD=data-keeper
    ports:
    - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

  app:
    build: .
    environment:
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=data-keeper
      - MYSQL_DATABASE=data-keeper
      - TZ=Europe/Moscow
    ports:
      - "3000:3000"  # или любой другой порт, который использует ваше приложение
    depends_on:
      - mysql  # гарантирует, что сначала будет запущен сервис mysql
    networks:
      - app-network
    restart: always

  web: # Имя сервиса
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Пробрасывает порт 8080 контейнера на 8080 хоста
    environment:
      NODE_ENV: production
    command: [ "npm", "run", "serve" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge