services:
  mysql:
    image: mariadb:10.5
    environment:
    - MYSQL_DATABASE=data-keeper
    - MYSQL_ROOT_PASSWORD=data-keeper
    ports:
#    - 33060:33060
    - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

  app:
    build: .
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=data-keeper
      - MYSQL_DATABASE=data-keeper
    ports:
      - "3000:3000"  # или любой другой порт, который использует ваше приложение
    depends_on:
      - mysql  # гарантирует, что сначала будет запущен сервис mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge