services:
  mysql:
    image: mysql:9.1
    environment:
    - MYSQL_DATABASE=data-keeper
    - MYSQL_ROOT_PASSWORD=data-keeper
    ports:
#    - 33060:33060
    - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

#  app:
#    build: .
#    network_mode: host
#    #entrypoint: tail -f /dev/null