services:
  mysql:
    image: mariadb:10.5
    environment:
    - MYSQL_DATABASE=data-keeper
    - MYSQL_ROOT_PASSWORD=data-keeper
    ports:
#    - 33060:33060
    - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network


#  app:
#    build: .
#    network_mode: host
#    #entrypoint: tail -f /dev/null

networks:
  app-network:
    driver: bridge